// Code generated by gen_typed.go; DO NOT EDIT.

//go:build (darwin || freebsd || linux || netbsd) && (amd64 || arm64)

package purego

import "unsafe"

// Bool conversion helpers
func boolToUintptr(b bool) uintptr {
	if b {
		return 1
	}
	return 0
}

func uintptrToBool(u uintptr) bool {
	return byte(u) != 0
}

func tryRegisterTypedGenerated(fptr any, cfn uintptr) bool {
	switch fn := fptr.(type) {
	case *func() int:
		*fn = func() int { return int(Syscall0(cfn)) }
		return true
	case *func() int32:
		*fn = func() int32 { return int32(Syscall0(cfn)) }
		return true
	case *func() int64:
		*fn = func() int64 { return int64(Syscall0(cfn)) }
		return true
	case *func() uint:
		*fn = func() uint { return uint(Syscall0(cfn)) }
		return true
	case *func() uint32:
		*fn = func() uint32 { return uint32(Syscall0(cfn)) }
		return true
	case *func() uint64:
		*fn = func() uint64 { return uint64(Syscall0(cfn)) }
		return true
	case *func() uintptr:
		*fn = func() uintptr { return Syscall0(cfn) }
		return true
	case *func() unsafe.Pointer:
		*fn = func() unsafe.Pointer { return unsafe.Pointer(Syscall0(cfn)) }
		return true
	case *func() bool:
		*fn = func() bool { return uintptrToBool(Syscall0(cfn)) }
		return true
	case *func():
		*fn = func() { Syscall0(cfn) }
		return true
	case *func(int) int:
		*fn = func(a int) int { return int(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(int) int32:
		*fn = func(a int) int32 { return int32(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(int) int64:
		*fn = func(a int) int64 { return int64(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(int) uint:
		*fn = func(a int) uint { return uint(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(int) uint32:
		*fn = func(a int) uint32 { return uint32(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(int) uint64:
		*fn = func(a int) uint64 { return uint64(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(int) uintptr:
		*fn = func(a int) uintptr { return Syscall1(cfn, uintptr(a)) }
		return true
	case *func(int) unsafe.Pointer:
		*fn = func(a int) unsafe.Pointer { return unsafe.Pointer(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(int) bool:
		*fn = func(a int) bool { return uintptrToBool(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(int):
		*fn = func(a int) { Syscall1(cfn, uintptr(a)) }
		return true
	case *func(int32) int:
		*fn = func(a int32) int { return int(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(int32) int32:
		*fn = func(a int32) int32 { return int32(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(int32) int64:
		*fn = func(a int32) int64 { return int64(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(int32) uint:
		*fn = func(a int32) uint { return uint(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(int32) uint32:
		*fn = func(a int32) uint32 { return uint32(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(int32) uint64:
		*fn = func(a int32) uint64 { return uint64(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(int32) uintptr:
		*fn = func(a int32) uintptr { return Syscall1(cfn, uintptr(a)) }
		return true
	case *func(int32) unsafe.Pointer:
		*fn = func(a int32) unsafe.Pointer { return unsafe.Pointer(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(int32) bool:
		*fn = func(a int32) bool { return uintptrToBool(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(int32):
		*fn = func(a int32) { Syscall1(cfn, uintptr(a)) }
		return true
	case *func(int64) int:
		*fn = func(a int64) int { return int(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(int64) int32:
		*fn = func(a int64) int32 { return int32(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(int64) int64:
		*fn = func(a int64) int64 { return int64(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(int64) uint:
		*fn = func(a int64) uint { return uint(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(int64) uint32:
		*fn = func(a int64) uint32 { return uint32(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(int64) uint64:
		*fn = func(a int64) uint64 { return uint64(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(int64) uintptr:
		*fn = func(a int64) uintptr { return Syscall1(cfn, uintptr(a)) }
		return true
	case *func(int64) unsafe.Pointer:
		*fn = func(a int64) unsafe.Pointer { return unsafe.Pointer(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(int64) bool:
		*fn = func(a int64) bool { return uintptrToBool(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(int64):
		*fn = func(a int64) { Syscall1(cfn, uintptr(a)) }
		return true
	case *func(uint) int:
		*fn = func(a uint) int { return int(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(uint) int32:
		*fn = func(a uint) int32 { return int32(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(uint) int64:
		*fn = func(a uint) int64 { return int64(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(uint) uint:
		*fn = func(a uint) uint { return uint(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(uint) uint32:
		*fn = func(a uint) uint32 { return uint32(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(uint) uint64:
		*fn = func(a uint) uint64 { return uint64(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(uint) uintptr:
		*fn = func(a uint) uintptr { return Syscall1(cfn, uintptr(a)) }
		return true
	case *func(uint) unsafe.Pointer:
		*fn = func(a uint) unsafe.Pointer { return unsafe.Pointer(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(uint) bool:
		*fn = func(a uint) bool { return uintptrToBool(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(uint):
		*fn = func(a uint) { Syscall1(cfn, uintptr(a)) }
		return true
	case *func(uint32) int:
		*fn = func(a uint32) int { return int(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(uint32) int32:
		*fn = func(a uint32) int32 { return int32(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(uint32) int64:
		*fn = func(a uint32) int64 { return int64(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(uint32) uint:
		*fn = func(a uint32) uint { return uint(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(uint32) uint32:
		*fn = func(a uint32) uint32 { return uint32(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(uint32) uint64:
		*fn = func(a uint32) uint64 { return uint64(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(uint32) uintptr:
		*fn = func(a uint32) uintptr { return Syscall1(cfn, uintptr(a)) }
		return true
	case *func(uint32) unsafe.Pointer:
		*fn = func(a uint32) unsafe.Pointer { return unsafe.Pointer(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(uint32) bool:
		*fn = func(a uint32) bool { return uintptrToBool(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(uint32):
		*fn = func(a uint32) { Syscall1(cfn, uintptr(a)) }
		return true
	case *func(uint64) int:
		*fn = func(a uint64) int { return int(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(uint64) int32:
		*fn = func(a uint64) int32 { return int32(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(uint64) int64:
		*fn = func(a uint64) int64 { return int64(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(uint64) uint:
		*fn = func(a uint64) uint { return uint(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(uint64) uint32:
		*fn = func(a uint64) uint32 { return uint32(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(uint64) uint64:
		*fn = func(a uint64) uint64 { return uint64(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(uint64) uintptr:
		*fn = func(a uint64) uintptr { return Syscall1(cfn, uintptr(a)) }
		return true
	case *func(uint64) unsafe.Pointer:
		*fn = func(a uint64) unsafe.Pointer { return unsafe.Pointer(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(uint64) bool:
		*fn = func(a uint64) bool { return uintptrToBool(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(uint64):
		*fn = func(a uint64) { Syscall1(cfn, uintptr(a)) }
		return true
	case *func(uintptr) int:
		*fn = func(a uintptr) int { return int(Syscall1(cfn, a)) }
		return true
	case *func(uintptr) int32:
		*fn = func(a uintptr) int32 { return int32(Syscall1(cfn, a)) }
		return true
	case *func(uintptr) int64:
		*fn = func(a uintptr) int64 { return int64(Syscall1(cfn, a)) }
		return true
	case *func(uintptr) uint:
		*fn = func(a uintptr) uint { return uint(Syscall1(cfn, a)) }
		return true
	case *func(uintptr) uint32:
		*fn = func(a uintptr) uint32 { return uint32(Syscall1(cfn, a)) }
		return true
	case *func(uintptr) uint64:
		*fn = func(a uintptr) uint64 { return uint64(Syscall1(cfn, a)) }
		return true
	case *func(uintptr) uintptr:
		*fn = func(a uintptr) uintptr { return Syscall1(cfn, a) }
		return true
	case *func(uintptr) unsafe.Pointer:
		*fn = func(a uintptr) unsafe.Pointer { return unsafe.Pointer(Syscall1(cfn, a)) }
		return true
	case *func(uintptr) bool:
		*fn = func(a uintptr) bool { return uintptrToBool(Syscall1(cfn, a)) }
		return true
	case *func(uintptr):
		*fn = func(a uintptr) { Syscall1(cfn, a) }
		return true
	case *func(unsafe.Pointer) int:
		*fn = func(a unsafe.Pointer) int { return int(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(unsafe.Pointer) int32:
		*fn = func(a unsafe.Pointer) int32 { return int32(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(unsafe.Pointer) int64:
		*fn = func(a unsafe.Pointer) int64 { return int64(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(unsafe.Pointer) uint:
		*fn = func(a unsafe.Pointer) uint { return uint(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(unsafe.Pointer) uint32:
		*fn = func(a unsafe.Pointer) uint32 { return uint32(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(unsafe.Pointer) uint64:
		*fn = func(a unsafe.Pointer) uint64 { return uint64(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(unsafe.Pointer) uintptr:
		*fn = func(a unsafe.Pointer) uintptr { return Syscall1(cfn, uintptr(a)) }
		return true
	case *func(unsafe.Pointer) unsafe.Pointer:
		*fn = func(a unsafe.Pointer) unsafe.Pointer { return unsafe.Pointer(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(unsafe.Pointer) bool:
		*fn = func(a unsafe.Pointer) bool { return uintptrToBool(Syscall1(cfn, uintptr(a))) }
		return true
	case *func(unsafe.Pointer):
		*fn = func(a unsafe.Pointer) { Syscall1(cfn, uintptr(a)) }
		return true
	case *func(bool) int:
		*fn = func(a bool) int { return int(Syscall1(cfn, boolToUintptr(a))) }
		return true
	case *func(bool) int32:
		*fn = func(a bool) int32 { return int32(Syscall1(cfn, boolToUintptr(a))) }
		return true
	case *func(bool) int64:
		*fn = func(a bool) int64 { return int64(Syscall1(cfn, boolToUintptr(a))) }
		return true
	case *func(bool) uint:
		*fn = func(a bool) uint { return uint(Syscall1(cfn, boolToUintptr(a))) }
		return true
	case *func(bool) uint32:
		*fn = func(a bool) uint32 { return uint32(Syscall1(cfn, boolToUintptr(a))) }
		return true
	case *func(bool) uint64:
		*fn = func(a bool) uint64 { return uint64(Syscall1(cfn, boolToUintptr(a))) }
		return true
	case *func(bool) uintptr:
		*fn = func(a bool) uintptr { return Syscall1(cfn, boolToUintptr(a)) }
		return true
	case *func(bool) unsafe.Pointer:
		*fn = func(a bool) unsafe.Pointer { return unsafe.Pointer(Syscall1(cfn, boolToUintptr(a))) }
		return true
	case *func(bool) bool:
		*fn = func(a bool) bool { return uintptrToBool(Syscall1(cfn, boolToUintptr(a))) }
		return true
	case *func(bool):
		*fn = func(a bool) { Syscall1(cfn, boolToUintptr(a)) }
		return true
	case *func(int, int) int:
		*fn = func(a, b int) int { return int(Syscall2(cfn, uintptr(a), uintptr(b))) }
		return true
	case *func(int32, int32) int32:
		*fn = func(a, b int32) int32 { return int32(Syscall2(cfn, uintptr(a), uintptr(b))) }
		return true
	case *func(int64, int64) int64:
		*fn = func(a, b int64) int64 { return int64(Syscall2(cfn, uintptr(a), uintptr(b))) }
		return true
	case *func(uint, uint) uint:
		*fn = func(a, b uint) uint { return uint(Syscall2(cfn, uintptr(a), uintptr(b))) }
		return true
	case *func(uint32, uint32) uint32:
		*fn = func(a, b uint32) uint32 { return uint32(Syscall2(cfn, uintptr(a), uintptr(b))) }
		return true
	case *func(uint64, uint64) uint64:
		*fn = func(a, b uint64) uint64 { return uint64(Syscall2(cfn, uintptr(a), uintptr(b))) }
		return true
	case *func(uintptr, uintptr) uintptr:
		*fn = func(a, b uintptr) uintptr { return Syscall2(cfn, a, b) }
		return true
	case *func(unsafe.Pointer, unsafe.Pointer) unsafe.Pointer:
		*fn = func(a, b unsafe.Pointer) unsafe.Pointer { return unsafe.Pointer(Syscall2(cfn, uintptr(a), uintptr(b))) }
		return true
	case *func(bool, bool) bool:
		*fn = func(a, b bool) bool { return uintptrToBool(Syscall2(cfn, boolToUintptr(a), boolToUintptr(b))) }
		return true
	case *func(unsafe.Pointer, int) int:
		*fn = func(a unsafe.Pointer, b int) int { return int(Syscall2(cfn, uintptr(a), uintptr(b))) }
		return true
	case *func(unsafe.Pointer, uintptr) uintptr:
		*fn = func(a unsafe.Pointer, b uintptr) uintptr { return Syscall2(cfn, uintptr(a), b) }
		return true
	case *func(int, int, int) int:
		*fn = func(a, b, c int) int { return int(Syscall3(cfn, uintptr(a), uintptr(b), uintptr(c))) }
		return true
	case *func(int32, int32, int32) int32:
		*fn = func(a, b, c int32) int32 { return int32(Syscall3(cfn, uintptr(a), uintptr(b), uintptr(c))) }
		return true
	case *func(int64, int64, int64) int64:
		*fn = func(a, b, c int64) int64 { return int64(Syscall3(cfn, uintptr(a), uintptr(b), uintptr(c))) }
		return true
	case *func(uint, uint, uint) uint:
		*fn = func(a, b, c uint) uint { return uint(Syscall3(cfn, uintptr(a), uintptr(b), uintptr(c))) }
		return true
	case *func(uint32, uint32, uint32) uint32:
		*fn = func(a, b, c uint32) uint32 { return uint32(Syscall3(cfn, uintptr(a), uintptr(b), uintptr(c))) }
		return true
	case *func(uint64, uint64, uint64) uint64:
		*fn = func(a, b, c uint64) uint64 { return uint64(Syscall3(cfn, uintptr(a), uintptr(b), uintptr(c))) }
		return true
	case *func(uintptr, uintptr, uintptr) uintptr:
		*fn = func(a, b, c uintptr) uintptr { return Syscall3(cfn, a, b, c) }
		return true
	case *func(unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) unsafe.Pointer:
		*fn = func(a, b, c unsafe.Pointer) unsafe.Pointer {
			return unsafe.Pointer(Syscall3(cfn, uintptr(a), uintptr(b), uintptr(c)))
		}
		return true
	case *func(bool, bool, bool) bool:
		*fn = func(a, b, c bool) bool {
			return uintptrToBool(Syscall3(cfn, boolToUintptr(a), boolToUintptr(b), boolToUintptr(c)))
		}
		return true
	case *func(int, int, int, int) int:
		*fn = func(a, b, c, d int) int { return int(Syscall4(cfn, uintptr(a), uintptr(b), uintptr(c), uintptr(d))) }
		return true
	case *func(int32, int32, int32, int32) int32:
		*fn = func(a, b, c, d int32) int32 {
			return int32(Syscall4(cfn, uintptr(a), uintptr(b), uintptr(c), uintptr(d)))
		}
		return true
	case *func(int64, int64, int64, int64) int64:
		*fn = func(a, b, c, d int64) int64 {
			return int64(Syscall4(cfn, uintptr(a), uintptr(b), uintptr(c), uintptr(d)))
		}
		return true
	case *func(uint, uint, uint, uint) uint:
		*fn = func(a, b, c, d uint) uint { return uint(Syscall4(cfn, uintptr(a), uintptr(b), uintptr(c), uintptr(d))) }
		return true
	case *func(uint32, uint32, uint32, uint32) uint32:
		*fn = func(a, b, c, d uint32) uint32 {
			return uint32(Syscall4(cfn, uintptr(a), uintptr(b), uintptr(c), uintptr(d)))
		}
		return true
	case *func(uint64, uint64, uint64, uint64) uint64:
		*fn = func(a, b, c, d uint64) uint64 {
			return uint64(Syscall4(cfn, uintptr(a), uintptr(b), uintptr(c), uintptr(d)))
		}
		return true
	case *func(uintptr, uintptr, uintptr, uintptr) uintptr:
		*fn = func(a, b, c, d uintptr) uintptr { return Syscall4(cfn, a, b, c, d) }
		return true
	case *func(int64, int64, int64, int64, int64, int64) int64:
		*fn = func(a, b, c, d, e, f int64) int64 {
			return int64(Syscall6(cfn, uintptr(a), uintptr(b), uintptr(c), uintptr(d), uintptr(e), uintptr(f)))
		}
		return true
	case *func(uintptr, uintptr, uintptr, uintptr, uintptr, uintptr) uintptr:
		*fn = func(a, b, c, d, e, f uintptr) uintptr { return Syscall6(cfn, a, b, c, d, e, f) }
		return true
	case *func(int64, int64, int64, int64, int64, int64, int64, int64) int64:
		*fn = func(a, b, c, d, e, f, g, h int64) int64 {
			return int64(Syscall8(cfn, uintptr(a), uintptr(b), uintptr(c), uintptr(d), uintptr(e), uintptr(f), uintptr(g), uintptr(h)))
		}
		return true
	case *func(uintptr, uintptr, uintptr, uintptr, uintptr, uintptr, uintptr, uintptr) uintptr:
		*fn = func(a, b, c, d, e, f, g, h uintptr) uintptr { return Syscall8(cfn, a, b, c, d, e, f, g, h) }
		return true
	}
	return false
}
